version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ENV_PATH=.env.production
      - DB_URL=postgres://postgres:password@db:5432/bookit
      - REDIS_URL=redis://redis:6379
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis