exports.routeParams = [
  {
    route: "users/register",
    params: {
      full_name: "",
      phone: "",
      email: "",
      password: "",
      oauth_provider: "",
      oauth_uid: "",
    },
    route: "users/register",
    params: {
      full_name: "",
      phone: "",
      email: "",
      password: "",
      oauth_provider: "",
      oauth_uid: "",
    },
    queryParams: [],
    authRequired: false,
    method: "post",
    tag: "users",
    method: "post",
    tag: "users",
  },
  {
    route: "users/register/user",
    params: {
      full_name: "",
      phone: "",
      email: "",
      password: "",
      oauth_provider: "",
      oauth_uid: "",
    },
    queryParams: [],
    authRequired: false,
    method: "post",
    tag: "users",
    method: "post",
    tag: "users",
  },
  {
    route: "users/register/admin",
    params: {
      full_name: "",
      phone: "",
      email: "",
      password: "",
      oauth_provider: "",
      oauth_uid: "",
    },
    queryParams: [],
    authRequired: false,
    method: "post",
    tag: "users",
    method: "post",
    tag: "users",
  },
  {
    route: "users/social-login",
    params: {
      full_name: "",
      phone: "",
      email: "",
      password: "",
      oauth_provider: "",
      oauth_uid: "",
    },
    queryParams: [],
    authRequired: false,
    method: "post",
    tag: "users",
  },
  {
    route: "users/login",
    params: {
      email: "",
      password: "",
      preferred_language: "",
    },
    queryParams: [],
    authRequired: false,
    method: "post",
    tag: "users",
  },
];
